#!/bin/bash

# Enable color support of ls and also add handy aliases.
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=always --group-directories-first'
    alias grep='grep --color=always'
    alias fgrep='fgrep --color=always'
    alias egrep='egrep --color=always'
fi

alias dir="ls --color=always -Altph"                              # List all files in dir.
alias mhd="ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%mem | head -16" # List top memory consuming processes.
alias chd="ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%cpu | head -16" # List top cpu consuming processes
alias lsm="ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%mem"
alias pks="apt search " #find a package based on name
alias pkfo="apt-cache show"
alias pss="gpg -d ~/.Private_Docs/pss.new.asc.asc | less"
alias less="less -R"
alias oyvey="shutdown now"
alias w3m="w3m -no-mouse" # -o auto_image=FALSE -no-graph "
alias py="python3"
alias rld="source ~/.bashrc"
alias fth="gforth"
alias hr="~/.bin/ghc"
alias swi="swipl"
alias aesthetic="figlet -d ~/repos/other/figlet-fonts -f wideterm.tlf "
alias fm="ranger "
alias hs=$'history'
alias hg="hs | grep"
alias svi="sudoedit"
alias gv="gvim"
alias vc="vi ~/.vimrc"
alias scc="gcc -Wall -Wextra -pedantic -Wno-comment -Wformat-nonliteral -Wformat-security -Wuninitialized -Winit-self -Warray-bounds=2  -Wenum-compare -Werror=implicit-function-declaration"

# Pathogen completion
complete -W "add remove upgrade" pathogen

# Pkm completion
complete -W "remove add update upgrade search info src" pkm

mkpss(){
	if [[ $# -eq 0 ]]; then
		apg -a 1 -m 20 -n 20 | sed '1q'
	else
		apg -a 1 -m "$1" -n 20 | sed '1q'
	fi
}

dfg(){
    job="$(jobs -l \
        | dmenuw -b -p '> ' -W "$(xdotool getwindowfocus)" -l 8 \
        | sed 's/Stopped/Paused/g;' \
        | awk -F'[\\[\\]]' '{ print $2 }')"

    [ -z "$job" ] && return
    fg "$job"
}

dhs(){
    command="$(history \
        | awk '{$1=""; print}' \
        | tac \
        | uniq -u \
        | dmenuw -b -l 8 -p '> ' -W "$(xdotool getwindowfocus)")"

    [ -z "$command" ] && return
    eval "$command"
}

bind -x '"":"dhs"'
bind -x '"":"dfg"'
