#!/bin/sh

case $BLOCK_BUTTON in
	1) 
		notify "$(acpi -i | head -1 | awk '{ print $5,$6,$7 }')" ;;
	*) return ;;
esac

bash "$HOME"/.config/i3/wrapper 1 0 "$(acpi -b | awk '{ print "[", substr($3,0,length($3)-1), "]", substr($4,0,length($4)-1) }')"
