#!/bin/sh

case $BLOCK_BUTTON in
	1) 
		notify "$(acpi -i | sed 1q | awk '{ print $5,$6,$7 }')" ;;
	*) return ;;
esac

bash "$HOME"/.config/i3/wrapper 4 0 "$(acpi -b | awk\
   	'{ status=substr($3,0,length($3)-1); print (status == "Discharging" ? "" : ""),substr($4,0,length($4)-1)   }')"
