#!/bin/bash
#vim:ft=sh:

bg=2
fg=0

status_icon(){
	case "$(cmus-remote -Q | awk '/status p/{ print $2 }')" in
		playing) echo -n " " ;;
		paused)  echo -n " " ;;
	esac
}

current(){
	all="$(cmus-remote -C "format_print %a\ |\ %t")"
	[[ ${#all} > 32 ]] && all="${all::32}..."
	echo $all
}

get_vol(){
	cmus-remote -Q | awk '/\<set vol_left\>/{ print $NF }'
}

get_all(){
	echo "$(status_icon) $(current) | $(get_vol)%"
}

if [[ -n $BLOCK_BUTTON ]]; then
	case $BLOCK_BUTTON in
		1) cmus-remote --pause
			bash $HOME/.config/i3/wrapper $bg $fg "$(get_all)"
		   ;; # Left click and update

		4) cmus-remote --volume +10%; 
		   ;; # Scroll up

		5) cmus-remote --volume -10%; 
		   ;; # Scroll down
		3)
			notify "Playing\n" "$(cmus-remote -Q | awk '/\<tag title\>|\<tag artist\>|\<tag album\>|\<tag date\>/{$1=$2=""; print $0 }')"
		;;
	esac
	source
fi

bash $HOME/.config/i3/wrapper $bg $fg "$(get_all)"
pkill -RTMIN+10 i3blocks
