#!/bin/bash

# sexy-numixdarkest
# sexy-dotshare
# sexy-gjm
# sexy-invisibone
# sexy-monokai
# sexy-vacuous2
# sexy-visibone-alt-2
# sexy-jasonwryan
# sexy-hund
# sexy-material
# sexy-dwmrob
# sexy-user-77-mashup-colors
# sexy-monokai
# sexy-navy-and-ivory
# sexy-tartan
# base16-gruvbox-pale
# base16-gruvbox-hard
# base16-material
# base16-onedark
# base16-tomorrow-night
# base16tooth
# base16-codeschool
# tempus_rift
# tempus_warp
# darktooth
# dkeg-bluetype
# dkeg-blend
# hybrid-material
# spacemacs
# vscode
# sexy-swayr
# base16-atelier-estuary
# base16-circus

# nbg="#151515"
# nfg="#f1ebeb"
# sbg="#383636"
# sfg="#f1ebeb"

# base16-material
# nbg="#263238"
# nfg="#d1cbc6"
# sbg="#3c4c54"
# sfg=$nfg

# base16-gruvbox-hard
# nbg="#1d2021"
# nfg="#d5c4a1"
# #sbg="#3f4f57"
# sbg="#757978"
# sfg=$nfg

# sexy-mikado
#nbg="#000000"
#nfg="#ffffff"
#sbg="#757978"
#sfg=$nfg

# neon
nbg="#0d1010"
nfg="#e5c8ac"
sbg="#2C4A54"
sfg=$nfg

font="terminus"
