#!/bin/bash

source $HOME/.cache/wal/colors.sh

option="$(python3 -c "print(chr(-1))" | dmenu -p "> " -fn terminus -i -nb $background -nf $foreground -sf $foreground -sb $color1)"

urxvt -e bash --init-file $HOME/.bashrc -c "$option"
