#!/bin/sh

# Get user input and run.

. "$HOME"/.cache/wal/colors.sh
option="$(printf "\x00" | dmenuw -p "» ")"
[ -z "$option" ] && exit
case "$option" in
	urxvt*) eval "$option" && exit ;;
esac
urxvt -e bash --init-file "$HOME"/.bashrc -c "$option"
