#!/bin/bash

nbg="#151515"
nfg="#f1ebeb"
sbg="#f1ebeb"
sfg="#151515"

option="$(echo -e '[logout]\n[shutdown]\n[bleachbit & shutdown]' | dmenu -i -l -b -nb $nbg -nf $nfg -sf $sfg -sb $sbg)"

optionq="$option"

if [ $optionq = "logout" ]; then
	i3-msg exit
fi

if [ $optionq = "shutdown" ]; then
	shutdown now
fi

if [ $optionq = "bleachbit & shutdown" ]; then
	bleachbit --preset -c && shutdown now
fi
