#!/bin/bash
# vim: filetype=sh:

source $HOME/.cache/wal/colors.sh

options="\
  System\n\
 菱 Restart i3\n\
  Lock machine\n\
   Network options\n\
   Usb devices\n\
 﫼 Logout\n
   Shutdown\n\
  Bleachbit+shutdown\n\
"

system(){
	options="\
         Search packages\n\
         Man-pages\n\
         Run"

    option="$(echo -e $options | dmenu -fn 'GohuFont Nerd Font-10.8' -i -nb $background -nf $foreground -sf $foreground -sb '#8f3f71')" # the chosen option

	case "$option" in
		*Search\ packages) pksearch                       ;;
		*Man-pages)        mansplain                      ;;
		*Run)              bash $HOME/.config/i3/dmenuCmd ;;
	esac
}

option="$(echo -e $options | dmenu -fn 'GohuFont Nerd Font-10.8' -i -nb $background -nf $foreground -sf $foreground -sb '#8f3f71')" # the chosen option

## Glob for actual option w/out icon ? yep, works.
case "$option" in
	*System)				system                                ;;
	*Lock\ machine) 		bash $HOME/.config/i3/lock.sh 		  ;;
	*Usb\ devices) 			$HOME/.config/i3/usbMount 			  ;;
	*Network\ options) 		bash $HOME/.config/i3/dmenuNetwork    ;;
	*Restart\ i3) 			pkill urxvt; i3-msg "restart" 		  ;;
	*Logout) 				i3-msg exit 						  ;;
	*Shutdown) 				shutdown now 						  ;;
	*Bleachbit+shutdown) 	bleachbit --preset -c && shutdown now ;;
esac



#options="lock machine\n\
#run\n\
#usb devices\n\
#network options\n\
#restart i3\n\
#logout\n\
#shutdown\n\
#bleachbit+shutdown"

#case "$option" in
#	"run") 					bash $HOME/.config/i3/dmenuCmd ;;
#	"usb devices") 			$HOME/.config/i3/usbMount ;;
#	"network options") 		bash $HOME/.config/i3/dmenuNetwork ;;
#	"restart i3") 			pkill urxvt; i3-msg "restart" ;;
#	"lock machine") 		bash $HOME/.config/i3/lock.sh ;;
#	"logout") 				i3-msg exit ;;
#	"shutdown") 			shutdown now ;;
#	"bleachbit+shutdown") 	bleachbit --preset -c && shutdown now ;;
#esac
