#!/bin/bash

nbg="#151515"
nfg="#f1ebeb"
sbg="#f1ebeb"
sfg="#151515"

option="$(echo -e 'run\nusb devices\nnetwork options\nrestart i3\nlogout\nshutdown\nbleachbit/shutdown' | dmenu -i -nb $nbg -nf $nfg -sf $sfg -sb $sbg)" # the chosen option
optionq="$option" # the option quoted for comparison

if [[ $optionq = "run" ]]; then
	$HOME/.config/i3/dmenuCmd
fi

if [[ $optionq = "network options" ]]; then
	$HOME/.config/i3/dmenuNetwork
fi

if [[ $optionq = "logout" ]]; then
	i3-msg exit
fi

if [[ $optionq = "shutdown" ]]; then
	shutdown now
fi

if [[ $optionq = "bleachbit & shutdown" ]]; then
	bleachbit --preset -c && shutdown now
fi

if [[ $optionq = "restart i3" ]]; then
	pkill ranger
	pkill calcurse
	pkill tmux
	pkill urxvt
	i3-msg "restart"
fi

