#!/bin/bash

source $HOME/.config/i3/dmenuColors

option="$(echo -e 'run\nusb devices\nnetwork options\nrestart i3\nlogout\nshutdown\nbleachbit/shutdown' | dmenu -fn $font -i -nb $nbg -nf $nfg -sf $sfg -sb $sbg)" # the chosen option
optionq="$option" # the option quoted for comparison

if [[ $optionq = "usb devices" ]]; then
	$HOME/.config/i3/usbMount
fi

if [[ $optionq = "run" ]]; then
	$HOME/.config/i3/dmenuCmd
fi

if [[ $optionq = "network options" ]]; then
	$HOME/.config/i3/dmenuNetwork
fi

if [[ $optionq = "logout" ]]; then
	i3-msg exit
fi

if [[ $optionq = "shutdown" ]]; then
	shutdown now
fi

if [[ $optionq = "bleachbit & shutdown" ]]; then
	bleachbit --preset -c && shutdown now
fi

if [[ $optionq = "restart i3" ]]; then
	pkill urxvt
	i3-msg "restart"
fi

