#!/bin/bash

source $HOME/.config/i3/dmenuColors

paths(){
	udisksctl status | python3 -c "
from sys import stdin;
status = [line.split() for line in stdin][3:]
for line in status:
	print('[%s]' % (line[0] + ' | ' + line[-1]))"
}

option="$(paths | dmenu -fn $font -i -nb $nbg -nf $nfg -sf $sfg -sb $sbg)"
