#!/bin/bash

nbg="#151515"
nfg="#f1ebeb"
sbg="#f1ebeb"
sfg="#151515"

paths(){
	udisksctl status | python3 -c "
from sys import stdin;
status = [line.split() for line in stdin][3:]
for line in status:
	print('[%s]' % (line[0] + ' | ' + line[-1]))"
}

option="$(paths | dmenu -i -nb $nbg -nf $nfg -sf $sfg -sb $sbg)"
