#!/bin/bash
# Grab the current weather from wttr.in using $LOCATION.
# Filter down into appropriate fields and print out.

if [[ -z $LOCATION ]]
then
	LOCATION=Derby
fi

echo -n "  "
main(){
	query="$(curl -s wttr.in/${LOCATION}?0T)"
	#echo "$query" | awk 'BEGIN{ORS=" "}/rain|cloud|sun/{ print $NF }'
	echo "$query" | awk 'BEGIN{ORS=" "}/°C/{ print $(NF-1),"°C" }'
	echo "$query" | awk 'BEGIN{ORS=" "}/km\/h/{ print $(NF-2),$(NF-1),"km/h" }'
	echo "$query" | awk 'BEGIN{ORS=" "}/mm/{ print $(NF-1),"mm" }'
}

main
