#!/bin/sh
#vim:ft=bash:

. "$HOME"/.cache/wal/colors.sh
bgcolor=$(eval echo "\$color${1}")
fgcolor=$(eval echo "\$background")

lpad=" "
rpad=" "

echo "\
<span font='10.5' bgcolor='${bgcolor}' fgcolor='${fgcolor}'>\
<big>$lpad</big>\
${*:3}\
<big>$rpad</big>\
</span>\
"
