#!/bin/bash
#vim:ft=bash:

source $HOME/.cache/wal/colors.sh
bgcolor=$(eval echo "\$color${1}")

#char=
#char=""
rchar=""
lchar=""
lpad=" "
rpad=" "

echo "\
<span fgcolor='${bgcolor}'>$rchar</span>\
<span bgcolor='${bgcolor}' fgcolor='${background}'>\
${lpad}${@:2}${rpad}\
<span fgcolor='${background}'>$lchar</span>\
</span>\
"
