#!/bin/bash

# Extract and print the current track information in a human
# palatable format using 'cmus-remote -Q'. Suitable for use with
# i3-blocks, etc. Allow autoplay and next track with mouse clicks.

cmus-remote
if [[ $? != 0 ]]; then
	echo -n "[]"
	return
fi

case $BLOCK_BUTTON in
	1) cmus-remote --pause    	 ;; # Left click
	4) cmus-remote --volume +10% ;; # Scroll up
	5) cmus-remote --volume -10% ;; # Scroll down
esac

case "$(cmus-remote -Q | grep "status p")" in
	"status paused")   echo -n "  " ;;
	"status playing")  echo -n "  " ;;
esac

cmus-remote -C "format_print %a\ ~\ %t"
