#!/bin/bash

# Simple script to notify using notify-send when the currently
# playing track changes in cmus.

qry(){
	while read -r line; do
		if [[ $line =~ 'tag title'* ]]; then
			echo -n ${line:10} 
		fi

	done <<< "$(cmus-remote -Q)"
}

lastStatus="$(qry)"

while true; do
	new="$(qry)"

	if [[ "$new" != "$lastStatus" ]]; then
		notify-send "Now playing:\n$new"
		lastStatus="$new"
	fi

	sleep 2

done
