#!/bin/bash

# Simple script to notify the user using notify-send 
# when the currently playing track changes in cmus.

get(){
	cmus-remote -C "format_print %a\ -\ %t"
}

ttl="$(get)"
while true
do
	test="$(get)"
	if [[ "$ttl" != "$test" ]]
	then
		bash notify " [Now playing]\n$test" -t 5
		ttl="$test"
	fi
	sleep 1
done

