#!/bin/sh

# Start compton. Use -s to specify shadowing.

# Compton options
# -C				 		no shadows on docks
# -c				 		shadows on windows
# -D				 		fade timing
# -r				 		shadow radius
# -o				 		shadow opacity
# -f				 		apply fade effects on window change
# -b				 		daemonise
# --blur-background  		blur background of transparent windows
# --blur-background-fixed	blur background with fixed blur radius.

# export XDG_CONFIG_HOME="$HOME/.config/compton/"
config="$HOME/.config/compton/"
case "$1" in 
	"-s")
		compton -z -C -c -f -D 9 -r 3 -o 0.4\
		  	--config "$config/compton.conf"
		;; 
	*) 
		compton -z -f -b -D 2 ;;
esac
