#!/bin/sh

#| Run dmenuw as a window switcher. Positions 
#| dmenu in the center of the screen.

# width=850
# lines=8
# lineheight=20
# 
# dimensions="$(xdpyinfo | awk '/dimensions/{ split($2,dimensions,"x"); print dimensions[1],dimensions[2] }')"
# x="$(echo "$dimensions" | awk '{ print $1 }')"
# y="$(echo "$dimensions" | awk '{ print $2 }')"
# x=$(( (x - width) / 2 ))
# y=$(( (y - (lineheight * (lines + 1))) / 2 ))

lsw | awk '{ $1=""; print }' | dmenuw -i -c -w 850 -l 8 | xargs -I{} wmctrl -a {}
