#!/bin/sh

#| Run dmenuw as a window switcher. 
#| Cap the number of dmenu lines at 8.

lines="$(lsw | wc -l)"
[ "$lines" -ge 8 ] && lines=8

lsw \
    | awk '{ $1=""; print }' \
    | dmenuw -i -wd 30 -l "$lines" \
    | xargs -I{} wmctrl -a {}
