#!/bin/sh

# Use dmenu to get a password. Can be piped to 
# `sudo -S` to run commands or programs as root.
# Example:
#    dPass | sudo -S synaptic

. "$HOME"/.cache/wal/colors.sh
[ -z "$1" ] && prompt="Password for $USER:" || prompt="$1"
dmenu -p "$prompt" -nf "$background" -nb "$background" -sf "$background" -sb "$color2" -c -w 850 <&- 2>/dev/null | cat
