#!/bin/sh

# Use dmenu to get a password. Can be piped to 
# `sudo -S` to run commands or programs as root.
# Example:
#    dPass | sudo -S synaptic

. "$HOME"/.cache/wal/colors.sh
caller="$(ps -o comm= -p "$(ps -o ppid= -p $$)")"
prompt="${1:-[$caller]}"
font="GohuFont Nerd Font-10.5:Regular"
"$HOME"/repos/personal/dmenu/dmenu -h 20 -p "$prompt" -fn "$font" -nf "$background" -nb "$background" -sf "$background" -sb "$foreground" <&- | cat
