#!/bin/sh

# Open feh with images scaled to a 
# sensible size based on the original,
# by specifying the (max) image width and
# calculating the height accordingly.

[ -z "$img_width" ] && img_width=900
geometry(){
	identify -format "%[fx:w]x%[fx:h]" "$1"
}

scale(){
	python3 -c "x, y = [ int(_) for _ in '$1'.split('x') ];\
ratio = x / y;\
print ($2 ,'x', int($2 / ratio), sep = '')"
}

case $# in
	0) echo "[ Need one or more images. ]" 
		exit 1
		;;
	*) 
		dimensions="$(geometry "$1")"; 
		dimensions="$(scale "$dimensions" $img_width)" 
		feh -g "$dimensions" "$1"
		exit 0
		;;
esac


