#!/bin/sh
# vim:set filetype=sh:

normal="$(tput sgr0)"
bold="$(tput bold)"
color1="$(tput setaf 1)"
color2="$(tput setaf 2)"
color3="$(tput setaf 3)"
color4="$(tput setaf 4)"
color5="$(tput setaf 5)"
color6="$(tput setaf 6)"
color7="$(tput setaf 7)"
color8="$(tput setaf 8)"
. /etc/os-release

uptime="$(uptime -p | sed 's/up //')"
mem=$(free -h | sed '2q;1d' | awk '{ print $3,"/",$2 }')
temp=$(sensors | awk '/CPU: /{ print $NF }')
cpu=$( (grep "model name" | uniq | sed 's/model name\s*\:\s*//') < /proc/cpuinfo)
packages="$(dpkg -l | wc -l)"

cat << EOF
${color2}o  ${color4}┏┓┓  ${color5}┳━┓  ${color8}┏━┓
${color2}┃  ${color4}┃┃┃  ${color5}┣━   ${color8}┃ ┃
${color2}┇  ${color4}┇┗┛  ${color5}┇    ${color8}┛━┛ ${normal}

${bold}[${color1}temp${normal}${bold}]      ${normal}$temp                 
${bold}[${color2}mem${normal}${bold}]       ${normal}$mem                  
${bold}[${color3}cpu${normal}${bold}]       ${normal}$cpu
${bold}[${color4}up${normal}${bold}]        ${normal}$uptime               
       
${bold}[${color5}shell${normal}${bold}]     ${normal}$SHELL                
${bold}[${color6}os${normal}${bold}]        ${normal}$NAME $VERSION_ID     
${bold}[${color7}wm${normal}${bold}]        ${normal}$XDG_CURRENT_DESKTOP  
${bold}[${color8}packages${normal}${bold}]  ${normal}$packages             

EOF
