#!/bin/bash
# vim: filetype=sh:

# Get a listing of man pages and run through dmenu to get
# a choice from the user. Awk out the section and pagename,
# then print the corresponding page to stdout then into
# zathura.

source $HOME/.cache/wal/colors.sh

opt="$(man -k . | dmenu -l 20 -fn Terminus-10 -i -nb $background -nf $foreground -sf $foreground -sb "#8f3f71")"

if [[ -n "$opt" ]]; then # An option was selected.
	name="$(echo $opt | awk '{ print $1 }')"
	section="$(echo $opt | awk '{ substr($2,2,length($2)-2) }')"

    man -Tpdf $page $name | zathura -
fi

