#!/bin/sh
# vim: filetype=sh:

# Get a listing of man pages and run through dmenu to get
# a choice from the user. Awk out the section and pagename,
# then print the corresponding page to stdout then into
# zathura.

. "$HOME"/.cache/wal/colors.sh

opt="$(man -k . | dmenuw -l 8 -i -fn Terminus-10 | awk '{ print substr($2,2,length($2)-2),$1 }')"
[ -n "$opt" ] && eval "man -Tpdf $opt" | zathura -
