#!/bin/sh

# Add more literate control of mic volume.
# examples:
#	$ mic [off|on]				# Turn the microphone on or off
#	$ mic vol sub|add [amount]  # Set volume
#	$ mic status				# Get on/off status and volume


on(){
	amixer set Capture cap > /dev/null
}

off(){
	amixer set Capture nocap > /dev/null
}

vol(){
	[ $# = 1 ] && amount=5
	[ $# != 1 ] && amount=$2
	case $1 in
		add) amixer set Capture "${amount}"%+ > /dev/null ;;
		sub) amixer set Capture "${amount}"%- > /dev/null ;;
	esac
}

status(){
	amixer get Capture | awk '/Front Left: Capture/{print $(NF - 2) " " $NF; }'
}

eval "$@"
