#!/bin/sh

# Open mpv with images scaled to a 
# sensible size based on the original,
# by specifying the desired image width 
# and calculating the height accordingly.
# Requires python3.

width=700

#lineSplit(){
#	echo "$1"
#	for x in "$1"
#	do
#		echo $x
#	done
#}
#
#filter(){
#	lineSplit "$1"
#}
#python3 -c "x, y = [ int(_) for _ in '$1'.split('x') ];ratio = x / y;print ($2 ,'x', int($2 / ratio), sep = '')"

geometry(){
	exiftool -ImageSize "$1"
}

scale(){
	awk -Fx "{ ratio=\$1 / \$2; print $2,'x',$2/ratio }"
}

if [ $# -eq 0 ]
then
	echo "* Need one or more files."
else
	dimensions="$(geometry "$1")"
	mpv --geometry="$(scale "$dimensions" $width)" "$1"
fi
