#!/bin/sh

. ~/.cache/wal/colors.sh

[ "$1" = -sound ] && sound=1 && shift

notify-send\
	-h string:fgcolor:"${foreground}"\
	-h string:frame_color:"#ffffff"\
	-h string:frame_width:5px\
   	-h string:bgcolor:"${background}"\
	-h string:font:"GohuFont Nerd Font 11"\
   	"$@"

[ -n "$sound"  ] && paplay /usr/share/sounds/freedesktop/stereo/dialog-warning.oga --volume=30000
