#!/bin/sh

pathogen_dir="$HOME/.vim/bundle"

remove(){
	var="$PWD"
	cd "$pathogen_dir"
	rm -rf "$1"
	cd "$var"
}

add(){
	var="$PWD"
	cd "$pathogen_dir"
	git clone "$1"
	cd "$var"
}

upgrade(){
	var="$PWD"
	cd "$pathogen_dir"
	remove "$1"
	add "$1"
	cd "$var"
}

info(){
    ls "$pathogen_dir"
}

eval "$@"
