#!/bin/sh

remove(){
	var="$PWD"
	cd "$HOME"/.vim/bundle
	rm -rf "$1"
	cd "$var"
}

add(){
	var="$PWD"
	cd "$HOME"/.vim/bundle
	git clone "$1"
	cd "$var"
}

upgrade(){
	remove "$1"
	add "$1"
}

eval "$@"
