#!/bin/bash

# Convert a pdf file to a series of png images,
# then stitch side by side. Requires imagemagick
# and pdftoppm.

main(){
	infile="$1"
	outfile="${infile::-4}"

	case $2 in
		""|"-h") mode="+append" ;;
		"-v") mode="-append" ;;
		*) echo "Usage: pdf2png <pdf> -[h|v]"
	esac

	pdftoppm "${infile}" "$outfile" -png # Convert to image series.
	temp="${outfile}-1.png"

	for file in ${outfile}-*.png # Using $temp as an accumulator.
	do
		case $file in
			$temp)  continue ;;  # Do nothing at first.
			*) ;;
		esac

		convert "$temp" "${file}" $mode "$temp"
	done

	mv "$temp" "${outfile}.png"
	for file in ${outfile}-*.png; do
		rm "$file"
	done
}

main "$@"
