#!/bin/bash

remove(){
	sudo apt-get purge $1
	sudo apt-get autoremove $1
}

add(){
	sudo apt-get update
	sudo apt-get install $1
}

update(){
	sudo apt-get update
}

upgrade(){
	sudo apt-get update
	sudo apt-get upgrade
}

search(){
	apt search $1
}

info(){
	apt-cache show $1
}

src(){
	apt-get source
}

$@
