#!/bin/sh
# vim: filetype=sh:

# Search though cached package info graphically with dmenu.
# Once an item is selected, display it in dmenu

. ~/.cache/wal/colors.sh

dm(){
	dmenuw -i -l 8
}

opt="$(apt-cache search . | dm | awk '{ print $1 }')"
[ -n "$opt" ] && apt-cache show "$opt" | awk '/^\s+/' | gvim -
