#!/bin/bash
# vim: filetype=sh:

# Search though cached package info graphically with dmenu.
# Once an item is selected, open it in dmenu

source ~/.cache/wal/colors.sh

dm(){
	dmenu -fn Terminus-10 -i -l 20 -nb $background -nf $foreground -sf $foreground -sb "#8f3f71"
}

opt="$(apt-cache search . | dm | awk '{ print $1 }')"
[[ -n $opt ]] && apt-cache show $opt | awk '/^\s+/{ print }' | dm 
