#!/bin/bash

for _ in {1..3}; do
        (                                                       \
          shuf                                                  \
        | sed $'/\'/d'                                          \
        | sed 1q                                                \
        | awk '{ printf toupper(substr($0,1,1)) substr($0,2) }' \
        ) < /usr/share/dict/words
done
