#!/bin/sh

#| Attempt to connect $display_ using xrandr.
#| Quit if $display_ is not specified. If no
#| external display is connected, revert to
#| just using the default.

[ -z "$display_" ] && display_=VGA-1

case "$1" in
    left|right) side="--${1}-of" ;;
	mirror)     side="--same-as" ;; 
	above)      side="--above" ;; 
	below)      side="--below" ;; 
	"")         side="--same-as" ;;
esac

case $(xrandr | awk -v display="$display_" '{ if (match($0, display)){ print $2 } }') in
	connected)	
		xrandr --output $display_ "$side" LVDS-1 --auto 
		"$HOME"/.fehbg
		;;

	disconnected) 
		xrandr --auto
		"$HOME"/.fehbg
		;;
esac
