#!/bin/sh

# Tabbed with colors sourced from pywal's cache
# directory.

. "$HOME"/.cache/wal/colors.sh
"$HOME"/repos/personal/tabbed/tabbed -t "$color4" -T "$background" -u "$color0" -U "$foreground" $@
# -g 1108x568 
