#!/bin/sh

# Turn the touchpad on and off.

option=$(synclient -l | grep TouchpadOff --color=no | awk '{ print substr($0,length($0)) }') 

[ $option = 0 ] && synclient TouchpadOff=1 && exit
synclient TouchpadOff=0
