#!/bin/sh

"$HOME"/Documents/code/repos/personal/dotfiles/move && echo "[Updated cached dotfiles]"

cd "$HOME"/Documents/code/repos/personal/dotfiles/
git add . && echo "[Staged files for commit]"

printf "Make commit [y/n] ?: "
read -r commit
case $commit in 
	y|yes) 
		printf 'Commit message: '; 
		read -r message
		git commit -m "$message" 
		
		printf 'Push to github [y/n] ?: '; 
		read -r push 
		
		case $push in
			y|yes) 
				./push
				
				;;
			
			n|no) ;;
			*) echo "[Unrecognised option, aborting]" ;;
		esac
		;;

	n|no) ;;

	*) echo "[Unrecognised option, aborting]" ;;
esac

