#!/usr/bin/env bash

bash $HOME/Documents/code/repos/personal/dotfiles/move
cd $HOME/Documents/code/repos/personal/dotfiles/
git add .

if [ "$(python3 -c print\(input\(\)\))" = "y" ]; then
	if [ "$#" = "0" ]; then
		git commit -m "-"
	else
		git commit -m "$1"
	fi
fi
