#!/usr/bin/env bash

echo -n "commit [y/n]:  "
result="$(python3 -c print\(input\(\)\))" 

bash $HOME/Documents/code/repos/personal/dotfiles/move
cd $HOME/Documents/code/repos/personal/dotfiles/
git add .

if [ "$result" = "y" ]; then
	if [ "$#" = "0" ]; then
		git commit -m "-"
	else
		git commit -m "$1"
	fi
fi
