#!/bin/sh

# Open urxvt instances using a running daemon. If there
# is no such running process, start it, then run urxvt
# with the specified arguments.
# URxvtd options:
# 	-q : quiet.
# 	-o : open display.
# 	-f : fork (exit script without hanging).

urxvtc "$@" && exit
urxvtd -q -o -f 
urxvtc "$@"
